"""Update articles 2021_08_22_14_27_01

Revision ID: 00346641e0b0
Revises: 0970774f0ed8
Create Date: 2021-08-22 14:27:02.067331

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "00346641e0b0"
down_revision = "0970774f0ed8"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "articles",
        sa.Column("id", sa.Integer(), nullable=True),
        sa.Column("title2", sa.String(), nullable=True),
    )
    op.drop_table("blogs")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "blogs",
        sa.Column("id", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("title", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column(
            "description", sa.VARCHAR(), autoincrement=False, nullable=True
        ),
    )
    op.drop_table("articles")
    # ### end Alembic commands ###
