"""Add serializers

Revision ID: 0e3f3b45815a
Revises: 9700e6bc3a20
Create Date: 2021-08-27 17:43:57.226449

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "0e3f3b45815a"
down_revision = "9700e6bc3a20"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "serializers",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=True),
        sa.Column("module_id", sa.Integer(), nullable=True),
        sa.Column(
            "type",
            sa.Enum(
                "GET_ITEM_RESPONSE",
                "GET_LIST_RESPONSE",
                "UPDATE_ITEM_REQUEST",
                "UPDATE_ITEM_RESPONSE",
                "CREATE_ITEM_REQUEST",
                "CREATE_ITEM_RESPONSE",
                "REMOVE_ITEM_REQUEST",
                "REMOVE_ITEM_RESPONSE",
                name="serializertype",
            ),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["module_id"],
            ["modules.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_serializers_id"), "serializers", ["id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_serializers_id"), table_name="serializers")
    op.drop_table("serializers")
    # ### end Alembic commands ###
