"""Update 2021_08_26_18_11_43

Revision ID: 0e7ffd5d2b31
Revises: ac09b7f0d473
Create Date: 2021-08-26 18:11:43.587089

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "0e7ffd5d2b31"
down_revision = "ac09b7f0d473"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
