"""Update applications

Revision ID: 1d233c749b72
Revises: 6c1ca39464c2
Create Date: 2021-09-03 15:58:58.650953

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "1d233c749b72"
down_revision = "6c1ca39464c2"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, "applications", ["name"])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "applications", type_="unique")
    # ### end Alembic commands ###
