"""Add statistic

Revision ID: 238e2ec33aa1
Revises: 9e1f798efd4d
Create Date: 2021-08-16 15:27:32.852495

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "238e2ec33aa1"
down_revision = "9e1f798efd4d"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "icons",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_icons_id"), "icons", ["id"], unique=False)
    op.create_index(op.f("ix_icons_name"), "icons", ["name"], unique=True)
    op.create_table(
        "cards",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(), nullable=True),
        sa.Column("value", sa.String(), nullable=True),
        sa.Column("icon_id", sa.Integer(), nullable=True),
        sa.Column("change", sa.String(), nullable=True),
        sa.Column("change_title", sa.String(), nullable=True),
        sa.Column("direction", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(
            ["icon_id"],
            ["icons.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("title"),
    )
    op.create_index(op.f("ix_cards_id"), "cards", ["id"], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_cards_id"), table_name="cards")
    op.drop_table("cards")
    op.drop_index(op.f("ix_icons_name"), table_name="icons")
    op.drop_index(op.f("ix_icons_id"), table_name="icons")
    op.drop_table("icons")
    # ### end Alembic commands ###
