"""Add card color

Revision ID: 257c4986352b
Revises: 238e2ec33aa1
Create Date: 2021-08-16 15:33:14.257235

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "257c4986352b"
down_revision = "238e2ec33aa1"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("cards", sa.Column("color", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("cards", "color")
    # ### end Alembic commands ###
