"""init

Revision ID: 33d21b7812fa
Revises: 
Create Date: 2021-08-26 11:46:07.573154

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "33d21b7812fa"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "constructor_applications",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=True),
        sa.Column("table_name", sa.String(), nullable=True),
        sa.Column("api_url", sa.String(), nullable=True),
        sa.Column("description", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_constructor_applications_id"),
        "constructor_applications",
        ["id"],
        unique=False,
    )
    op.create_table(
        "constructor_data_types",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_constructor_data_types_id"),
        "constructor_data_types",
        ["id"],
        unique=False,
    )
    op.create_table(
        "constructor_fields",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=True),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column("data_type_id", sa.Integer(), nullable=True),
        sa.Column("application_id", sa.Integer(), nullable=True),
        sa.Column("foreign_key_id", sa.Integer(), nullable=True),
        sa.Column("is_primary_key", sa.Boolean(), nullable=True),
        sa.Column("is_index", sa.Boolean(), nullable=True),
        sa.Column("size", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["application_id"],
            ["constructor_applications.id"],
        ),
        sa.ForeignKeyConstraint(
            ["data_type_id"],
            ["constructor_data_types.id"],
        ),
        sa.ForeignKeyConstraint(
            ["foreign_key_id"],
            ["constructor_fields.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "name", "application_id", name="application field unique"
        ),
    )
    op.create_index(
        op.f("ix_constructor_fields_id"),
        "constructor_fields",
        ["id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_constructor_fields_id"), table_name="constructor_fields"
    )
    op.drop_table("constructor_fields")
    op.drop_index(
        op.f("ix_constructor_data_types_id"),
        table_name="constructor_data_types",
    )
    op.drop_table("constructor_data_types")
    op.drop_index(
        op.f("ix_constructor_applications_id"),
        table_name="constructor_applications",
    )
    op.drop_table("constructor_applications")
    # ### end Alembic commands ###
