"""Add default values for users

Revision ID: 37002634a6d6
Revises: ca1c664f68ce
Create Date: 2021-06-25 17:30:51.609135

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "37002634a6d6"
down_revision = "ca1c664f68ce"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
