"""Add icons

Revision ID: 5fc80af037f2
Revises: 9ba786e1bb8a
Create Date: 2021-09-02 15:21:20.970829

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "5fc80af037f2"
down_revision = "9ba786e1bb8a"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
