"""Update 2021_08_26_18_21_53

Revision ID: 624b1a4be037
Revises: 0e7ffd5d2b31
Create Date: 2021-08-26 18:21:53.359715

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "624b1a4be037"
down_revision = "0e7ffd5d2b31"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
