"""Update 2021_08_27_13_05_29

Revision ID: 6eb9f72db4f0
Revises: 9c7ed601db2a
Create Date: 2021-08-27 13:05:29.530440

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "6eb9f72db4f0"
down_revision = "9c7ed601db2a"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "articles", sa.Column("blog_id", sa.Integer(), nullable=True)
    )
    op.create_foreign_key(None, "articles", "blogs", ["blog_id"], ["id"])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "articles", type_="foreignkey")
    op.drop_column("articles", "blog_id")
    # ### end Alembic commands ###
