"""Update data_type model at 2021-02

Revision ID: 95b4c9870f8f
Revises: a8d1203491bd
Create Date: 2021-08-21 21:02:03.831866

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "95b4c9870f8f"
down_revision = "a8d1203491bd"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table("data_type", sa.Column("id", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("data_type")
    # ### end Alembic commands ###
