"""Add modules

Revision ID: 9700e6bc3a20
Revises: 9cdf223a5f59
Create Date: 2021-08-27 17:40:52.812690

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "9700e6bc3a20"
down_revision = "9cdf223a5f59"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "modules",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("application_id", sa.Integer(), nullable=True),
        sa.Column("name", sa.String(), nullable=True),
        sa.Column("icon", sa.String(), nullable=True),
        sa.Column("url", sa.String(), nullable=True),
        sa.Column("api", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(
            ["application_id"],
            ["applications.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_modules_id"), "modules", ["id"], unique=False)
    op.add_column("applications", sa.Column("url", sa.String(), nullable=True))
    op.add_column(
        "applications", sa.Column("icon", sa.String(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("applications", "icon")
    op.drop_column("applications", "url")
    op.drop_index(op.f("ix_modules_id"), table_name="modules")
    op.drop_table("modules")
    # ### end Alembic commands ###
