"""Update 2021_08_27_12_51_52

Revision ID: 9c7ed601db2a
Revises: 624b1a4be037
Create Date: 2021-08-27 12:51:52.607234

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "9c7ed601db2a"
down_revision = "624b1a4be037"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
