"""Init project

Revision ID: 9cdf223a5f59
Revises: 
Create Date: 2021-08-27 15:33:58.701166

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "9cdf223a5f59"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "applications",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=True),
        sa.Column("description", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_applications_id"), "applications", ["id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_applications_id"), table_name="applications")
    op.drop_table("applications")
    # ### end Alembic commands ###
