"""Add field template unique

Revision ID: a8d1203491bd
Revises: 7a8a4e786bc0
Create Date: 2021-08-17 17:30:11.434225

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "a8d1203491bd"
down_revision = "7a8a4e786bc0"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(
        "template field unique", "constructor_fields", ["name", "template_id"]
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "template field unique", "constructor_fields", type_="unique"
    )
    # ### end Alembic commands ###
