"""Update articles 2021_08_22_14_29_02

Revision ID: a8f8dd51ba37
Revises: ba14c0d2d77f
Create Date: 2021-08-22 14:29:02.719878

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "a8f8dd51ba37"
down_revision = "ba14c0d2d77f"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("articles", sa.Column("name57", sa.Integer(), nullable=True))
    op.drop_column("articles", "name5")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "articles",
        sa.Column("name5", sa.INTEGER(), autoincrement=False, nullable=True),
    )
    op.drop_column("articles", "name57")
    # ### end Alembic commands ###
