"""Update 2021_08_26_16_32_49

Revision ID: ac09b7f0d473
Revises: 33d21b7812fa
Create Date: 2021-08-26 16:32:49.393214

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "ac09b7f0d473"
down_revision = "33d21b7812fa"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "articles",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(), nullable=True),
        sa.Column("description", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "blogs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("blogs")
    op.drop_table("articles")
    # ### end Alembic commands ###
