"""Add templates

Revision ID: afeb3d856cc5
Revises: 257c4986352b
Create Date: 2021-08-17 11:05:14.560726

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "afeb3d856cc5"
down_revision = "257c4986352b"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "constructor_data_types",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_constructor_data_types_id"),
        "constructor_data_types",
        ["id"],
        unique=False,
    )
    op.create_table(
        "constructor_templates",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=True),
        sa.Column("description", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_constructor_templates_id"),
        "constructor_templates",
        ["id"],
        unique=False,
    )
    op.create_table(
        "constructor_fields",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=True),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column("data_type_id", sa.Integer(), nullable=True),
        sa.Column("template_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["data_type_id"],
            ["constructor_data_types.id"],
        ),
        sa.ForeignKeyConstraint(
            ["template_id"],
            ["constructor_templates.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_constructor_fields_id"),
        "constructor_fields",
        ["id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_constructor_fields_id"), table_name="constructor_fields"
    )
    op.drop_table("constructor_fields")
    op.drop_index(
        op.f("ix_constructor_templates_id"), table_name="constructor_templates"
    )
    op.drop_table("constructor_templates")
    op.drop_index(
        op.f("ix_constructor_data_types_id"),
        table_name="constructor_data_types",
    )
    op.drop_table("constructor_data_types")
    # ### end Alembic commands ###
