"""Add icons

Revision ID: b630f02a9ba8
Revises: 5fc80af037f2
Create Date: 2021-09-02 15:22:03.881714

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "b630f02a9ba8"
down_revision = "5fc80af037f2"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "icons",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_icons_id"), "icons", ["id"], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_icons_id"), table_name="icons")
    op.drop_table("icons")
    # ### end Alembic commands ###
