"""Update articles 2021_08_22_14_28_31

Revision ID: ba14c0d2d77f
Revises: bfdb1b461aac
Create Date: 2021-08-22 14:28:31.395577

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "ba14c0d2d77f"
down_revision = "bfdb1b461aac"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("articles", sa.Column("name5", sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("articles", "name5")
    # ### end Alembic commands ###
