"""Update articles 2021_08_22_14_27_18

Revision ID: bfdb1b461aac
Revises: 00346641e0b0
Create Date: 2021-08-22 14:27:18.873369

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "bfdb1b461aac"
down_revision = "00346641e0b0"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("articles", sa.Column("title23", sa.String(), nullable=True))
    op.drop_column("articles", "title2")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "articles",
        sa.Column("title2", sa.VARCHAR(), autoincrement=False, nullable=True),
    )
    op.drop_column("articles", "title23")
    # ### end Alembic commands ###
