"""Update user model

Revision ID: ca1c664f68ce
Revises: a0077ec0eb43
Create Date: 2021-06-23 18:44:47.664608

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "ca1c664f68ce"
down_revision = "a0077ec0eb43"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("first_name", sa.String(), nullable=True))
    op.add_column("users", sa.Column("last_name", sa.String(), nullable=True))
    op.add_column("users", sa.Column("patronymic", sa.String(), nullable=True))
    op.add_column("users", sa.Column("avatar", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "avatar")
    op.drop_column("users", "patronymic")
    op.drop_column("users", "last_name")
    op.drop_column("users", "first_name")
    # ### end Alembic commands ###
