"""Add field foreign key id

Revision ID: e9f3441413b4
Revises: a8d1203491bd
Create Date: 2021-08-22 18:54:41.690226

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "e9f3441413b4"
down_revision = "a8d1203491bd"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "constructor_fields",
        sa.Column("foreign_key_id", sa.Integer(), nullable=True),
    )
    op.create_foreign_key(
        None,
        "constructor_fields",
        "constructor_fields",
        ["foreign_key_id"],
        ["id"],
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "constructor_fields", type_="foreignkey")
    op.drop_column("constructor_fields", "foreign_key_id")
    # ### end Alembic commands ###
