"""Update 2021_08_27_13_06_43

Revision ID: f200a2a0b9a5
Revises: 6eb9f72db4f0
Create Date: 2021-08-27 13:06:43.909976

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "f200a2a0b9a5"
down_revision = "6eb9f72db4f0"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
